### ISSUE TITLE
Rollup integration

### ISSUE THREAD

**Issue by JoviDeCroock** [JoviDeCroock/prefresh#20]

**Comment by calebeby** [comment]
Rollup doesn't support hmr out of the box, how would this work?

**Comment by JoviDeCroock** [comment]
I think this is supported by [`nollup`](https://github.com/PepsRyuu/nollup)

**Comment by PepsRyuu** [comment]
Just saw this! I'll try to write a plugin later this evening! :) Really excited to try this out!

**Comment by JoviDeCroock** [comment]
@PepsRyuu That would be really awesome, thank you so much for chiming in here!

**Comment by PepsRyuu** [comment]
https://github.com/PepsRyuu/nollup/commit/4ea964c0949a3e02ce1239894f66604805dcd87b

Rough prototype. At the moment it does the following:

* Replaces hook component, but loses state.
* Page refreshes on changing class components.
* Page refreshes on changing non-hook functional components.

Looks like the Babel plugin only adds ```$RefreshSig$``` before hook components, adds ```$RefreshReg$``` after functional components, and doesn't do anything for class components. The lack of RefreshSig seems to be causing the page to refresh because the components don't get added to signatures weakmap. 

Any tips?

**Comment by JoviDeCroock** [comment]
It should add it for both, https://astexplorer.net/#/gist/f792ef6b7fbfdf33f9124dd5d4fbb6fc/598d72bef20bd8f7413a2fad3ad82f1f102cad59

Page refreshing means that we are hitting errors, since components and non-hook functional components should work without the babel plugin even.

**Comment by PepsRyuu** [comment]
I have that part working (except the losing the state part). More so wondering if these are behaving as expected by causing a page refresh: https://astexplorer.net/#/gist/8d70f0b0300e08564f6c8fb6693ae573/bb9418420f40a2bb32ae7263b497494fccc358f3

**Comment by JoviDeCroock** [comment]
When the signatures are a missmatch they revert to a `window.location.reload()` since I'm figuring out an issue with custom hooks at this moment.

**Comment by JoviDeCroock** [comment]
Update: I have a branch where I've fixed the last issues, I'll publish the updated `@prefresh/utils` soon so we can all benefit from this. I've been really focussed on making it work in webpack and I'm going to try and get more into all the rest now. Thank you so much for the effort already @PepsRyuu this means a lot to me!

**Comment by JoviDeCroock** [comment]
Hey @PepsRyuu 

Happy being able to come back to you about this, so I've changed a few things in the webpack implementation and released `@prefresh/utils` to ensure we can all benefit from it.

First of all I moved all the `module.hot` stuff into a loader, felt more reliable and consistent, you can read the implementation [here](https://github.com/JoviDeCroock/prefresh/blob/master/packages/webpack/src/loader/runtime.js) there isn't that much special about it, it just uses the [utils](https://github.com/JoviDeCroock/prefresh/blob/master/packages/utils/src/compareSignatures.js) to compare [`signatures`](https://github.com/JoviDeCroock/prefresh/blob/master/packages/webpack/src/utils/createTemplate.js#L9) we generate these in where the former implementation was situated. The method to sign gets called by the [`react-refresh/babel`](https://github.com/facebook/react/blob/master/packages/react-refresh/src/ReactFreshBabelPlugin.js) plugin

**Comment by PepsRyuu** [comment]
Updated the branch: https://github.com/PepsRyuu/nollup/commit/d69bcf695f00b23c18a096bd86811e6bc222cf15

It works amazingly! Class components, functional and hook components all work. It works better than React Refresh because even class components preserve their state, really cool! 😁

There's one issue I had with integration: I had to copy the implementation of ```@prefresh/utils``` because it's written in CJS. Needs to be written in ESM so it can be imported without using the CommonJS plugin.

Fantastic work! ❤

**Comment by PepsRyuu** [comment]
https://github.com/JoviDeCroock/prefresh/pull/27 :D

**Comment by JoviDeCroock** [comment]
This will be released later today as `@prefresh/nollup`

**Comment by PepsRyuu** [comment]
https://github.com/PepsRyuu/nollup/tree/master/examples/example-preact Example updated using the newly released package! :D Thank you!
