### ISSUE TITLE
@prefresh injected code fails on pnpm

### ISSUE THREAD

**Issue by liflovs** [JoviDeCroock/prefresh#328]
Started project with vite + preact -> instantly got into issue using pnpm:
`10:04:08 [vite] Internal server error: Failed to resolve import "@prefresh/vite/runtime" from "src\app.jsx". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/Users/lflse/Projects/lifl/test/vite-project/src/app.jsx
  1  |  import '@prefresh/vite/runtime';
     |          ^
  2  |  import { flushUpdates } from '@prefresh/vite/utils';
  3  |  let prevRefreshReg;`

Should have been fixed according to  #75, a regression maybe?

**Comment by JoviDeCroock** [comment]
Just checked on runpkg, everything looks good

**Comment by cyyynthia** [comment]
This is related to the bug I've been encountering and looked into [here](https://github.com/JoviDeCroock/prefresh/issues/319#issuecomment-817156403). TL;DR is that if prefresh/vite isn't a direct dependency of your project (e.g.: it's a dependency of Preact's vite preset), you also need to install it because of pnpm's strictness around package access.

**Comment by liflovs** [comment]
@cyyynthia thanks, that was the issue! I guess that fact should be noted in the docs. 

P.S. Borkenware - nice stuff :)

**Comment by cyyynthia** [comment]
I just looked back at my attempt to fix this compatibility problem and I completely forgot Rollup accepts a 2nd argument for `resolve`, and this 2nd argument seems to be able to fix the problem without the problems I had in my original approach. 🎉

Now the only problem I face is able to conditionally use `__filename` or `import.meta.url` for the mjs output, since bundt doesn't handle that and simply having `import.meta` mentioned in the file yields a SyntaxError when using commonjs. I'll open a draft PR in a bit with what I have for now.
