### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by JoviDeCroock** [JoviDeCroock/prefresh#41]
We need puppeteer tests for

- [x] webpack
- [x] next.js
- [x] vite
- [x] snowpack
- [x] nollup

We need tests for refreshing:
- [x] custom hook
- [x] JSX

**Comment by PepsRyuu** [comment]
Just thinking about this more (still trying to get the current tests running on my laptop), do you think it might be worthwhile having a look to have a common set of test cases and run the same ones for each bundler? Something like the following:

```
[vite, snowpack, nollup].forEach(engine => {
    beforeEach(() => {
          // start dev server
     });

    describe('some test case', () => {
         it ('should update');
    });
});
```
Would reduce a lot of duplication. Fixtures might have to be duplicated though because of different ```index.html``` files though. Or do you think it would be better to keep tests separate for the time being?

**Comment by JoviDeCroock** [comment]
I think there's value in having a general test suite so we can test it all at once but it's going to be really hard to find the right abstraction to make all integrations work.
